[build]
base = "/"
publish = "/build/"
command = "npm run-script build"


[[headers]]
    for = "/.well-known/stellar.toml"
    [headers.values]
        Content-Type = "text/plain"
        Access-Control-Allow-Origin = "*"